### ISSUE TITLE
Surface Laptop Go Repostory? 

### ISSUE THREAD

**Issue by piticrobert** [dclive/AsusB450M-II_Ryzen5600X_Hackintosh#2]
Hello, I saw you had deleted the Surface Laptop Go. Can you post it back? Or a link of last EFI?

**Comment by piticrobert** [comment]
I was working with your EFI, but I don't have a back up off it :(

**Comment by dclive** [comment]
Sorry; I didn't keep any copies that I know are working.  I tried to give 3 months notice; apologies!
